data_configs:
  lang_pair: "en-zh"
  train_data:
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_train/train.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_train/train.mt"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_train/train.mt_tag"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_train/train.hter"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_train/train.pe"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_train/train.mt-pe.alignments"
  valid_data:
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_dev/dev.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_dev/dev.mt"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_dev/dev.mt_tag"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_dev/dev.hter"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_dev/dev.pe"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_dev/dev.mt-pe.alignments"
  test_data:
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_test/test.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_test/test.mt"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_test/test.mt_tag"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_test/test.hter"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_test/test.pe"
    - "/home/data_ti4_c/yanym/data/wmt21/post-editing/mello_version_enzh/qe_test/test.mt-pe.alignments"
  vocabularies:
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/vocab.en"
      max_n_words: -1
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/vocab.zh"
      max_n_words: -1
  max_len:
    - -1
    - -1
  num_refs: 1
  eval_at_char_level: false

discriminator_configs:
  model: Discriminator
  n_layers: 6
  n_head: 8
  n_labels: 3
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.0001
  weight_decay: 0
  grad_clip: 1.0
  optimizer_params: ~
  schedule_method: ~
  scheduler_configs:
    d_model: 512
    warmup_steps: 100

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: false
  use_bucket: false
  buffer_size: 1000
  batching_key: "samples"
  disp_freq: 60
  save_freq: 1200
  num_kept_checkpoints: 1
  update_cycle: 30
  batch_size: 2
  loss_valid_freq: 30
  early_stop_patience: 30
  loss_real_lambda: 1.0
  loss_parallel_lambda: 0.0
  loss_switch_lambda: 0.0
  cl_lambda_parallel: 0.0
  cl_lambda_switch: 1.0