data_configs:
  lang_pair: "en-zh"
  train_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/train.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/train.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/train.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/train.hter"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result_qe_train/qe_train_pred.tag"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result_qe_train/qe_train_pred.hter"
  valid_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.hter"
  test_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/test.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/test.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/test.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/test.hter"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result/test.tag"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result/test.hter"
  parallel_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel/parallel_train.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel/parallel_train.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel/parallel_train.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel/parallel_train.hter"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result_parallel/parallel_pred.tag"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result_parallel/parallel_pred.hter"
  parallel_pseudo_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/pseudo/pseudo_train.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/pseudo/pseudo_train.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/pseudo/pseudo_train.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/pseudo/pseudo_train.hter"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result_pseudo/pseudo_pred.tag"
    - "/home/data_ti4_c/yanym/save/enzh/discriminator_finetuned_256_with_parallel_cl_aug10/test_result_pseudo/pseudo_pred.hter"
  vocabularies:
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/vocab.en"
      max_n_words: -1
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/vocab.zh"
      max_n_words: -1
  max_len:
    - -1
    - -1
  num_refs: 1
  eval_at_char_level: false

discriminator_configs:
  model: Discriminator
  n_layers: 6
  n_head: 8
  n_labels: 3
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.0001
  weight_decay: 0
  grad_clip: 1.0
  optimizer_params: ~
  schedule_method: ~
  scheduler_configs:
    d_model: 512
    warmup_steps: 100

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: false
  use_bucket: false
  buffer_size: 1000
  batch_size: 1
  batching_key: "samples"
  update_cycle: 30
  valid_batch_size: 1
  disp_freq: 60
  save_freq: 1200
  num_kept_checkpoints: 1
  loss_valid_freq: 1200
  early_stop_patience: 10
