data_configs:
  lang_pair: "en-zh"
  train_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_train.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_train.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_train.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_train.hter"
  valid_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_dev.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_dev.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_dev.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/parallel_plus_pseudo/parallel_pseudo_dev.hter"
  vocabularies:
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/mello_version/vocab.en"
      max_n_words: -1
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/mello_version/vocab.zh"
      max_n_words: -1
  max_len:
    - 120
    - 120
  num_refs: 1
  eval_at_char_level: false

discriminator_configs:
  model: Discriminator
  n_layers: 6
  n_head: 8
  n_labels: 3
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

generator_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 100
  shuffle: true
  use_bucket: true
  batch_size: 8000
  batching_key: "tokens"
  update_cycle: 20
  valid_batch_size: 20
  disp_freq: 80
  save_freq: 80
  num_kept_checkpoints: 1
  loss_valid_freq: 80
  early_stop_patience: 20
