data_configs:
  lang_pair: "en-zh"
  train_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_3500.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_3500.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_3500.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_3500.hter"
  valid_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_dev_pseudo.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_dev_pseudo.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_dev_pseudo.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_dev_pseudo.hter"
  toy_train_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_toy.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_toy.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_toy.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_pseudo_toy.hter"
  finetune_toy_train_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_toy.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_toy.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_toy.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/qe_train_pseudo/qe_train_toy.hter"
  finetune_valid_data:
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.src.BPE"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.mt"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.tag"
    - "/home/data_ti4_c/yanym/data/wmt20/enzh/task2/mello_version/dev.hter"
  vocabularies:
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/mello_version/vocab.en"
      max_n_words: -1
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/mello_version/vocab.zh"
      max_n_words: -1
  max_len:
    - 120
    - 120
  num_refs: 1
  eval_at_char_level: false

discriminator_configs:
  model: Discriminator
  n_layers: 6
  n_head: 8
  n_labels: 3
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

generator_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.0001
  grad_clip: 1.0
  optimizer_params: ~
  schedule_method: ~
  scheduler_configs:
    d_model: 512
    warmup_steps: 100

training_configs:
  seed: 1234
  max_epochs: 100
  shuffle: true
  use_bucket: false
  buffer_size: 1000
  batch_size: 1
  batching_key: "samples"
  update_cycle: 30
  valid_batch_size: 1
  disp_freq: 60
  save_freq: 20
  num_kept_checkpoints: 1
  loss_valid_freq: 20
  early_stop_patience: 10
