data_configs:
  lang_pair: "en-zh"
  train_data:
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_parallel_train.src.BPE"
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_pseudo_train.mt.BPE"
    - "/data1/yanym/data/toy_contrastive/data_1000/toy.index"
  valid_data:
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_pseudo_train.src.BPE"
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_pseudo_train.mt.BPE"
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_pseudo_train.tag.BPE"
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_pseudo_train.hter"
    - "/data1/yanym/data/toy_contrastive/data_1000/toy_parallel_train.src.BPE"
  vocabularies:
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/mello_version/vocab.en"
      max_n_words: -1
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/data/wmt20/enzh/parallel/mello_version/vocab.zh"
      max_n_words: -1
  max_len:
    - 120
    - 120
  num_refs: 1
  eval_at_char_level: false

discriminator_configs:
  model: Discriminator
  n_layers: 6
  n_head: 8
  n_labels: 3
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

generator_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.1
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 1000

training_configs:
  seed: 1234
  max_epochs: 1000
  shuffle: true
  use_bucket: false
  batch_size: 1000
  batching_key: "tokens"
  update_cycle: 1
  valid_batch_size: 5
  disp_freq: 2
  save_freq: 2
  num_kept_checkpoints: 1
  loss_valid_freq: 10
  early_stop_patience: 20
  valid_cl: false
  loss_real_lambda: 1
  loss_parallel_lambda: 0
  cl_lambda: 0