data_configs:
  lang_pair: "en-ru"
  train_data:
    - "/home/user_data55/cuiq/QE_IJCAI/data/Brain/enru/corpus.en.BPE"
    - "/home/user_data55/cuiq/QE_IJCAI/data/Brain/enru/corpus.ru.BPE"
  valid_data:
    - "/home/user_data55/cuiq/QE_IJCAI/data/Brain/enru/dev_corpus.en.BPE"
    - "/home/user_data55/cuiq/QE_IJCAI/data/Brain/enru/dev_corpus.ru.BPE"
  vocabularies:
    - type: "bpe"
      dict_path: "/home/user_data55/cuiq/QE_IJCAI/data/Brain/enru/vocab.en.json"
      max_n_words: -1
    - type: "bpe"
      dict_path: "/home/user_data55/cuiq/QE_IJCAI/data/Brain/enru/vocab.ru.json"
      max_n_words: -1
  max_len:
    - 120
    - 120
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 256
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 200
  shuffle: true
  use_bucket: true
  batch_size: 8000
  batching_key: "tokens"
  update_cycle: 20
  valid_batch_size: 20
  disp_freq: 200
  save_freq: 200
  num_kept_checkpoints: 1
  loss_valid_freq: 200
  early_stop_patience: 20