data_configs:
  lang_pair: "en-de"
  train_data:
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/train.src.BPE"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/train.mt"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/train.tag"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/train.hter"
  valid_data:
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/dev.src.BPE"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/dev.mt"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/dev.tag"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/dev.hter"
  test_data:
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/test.src.BPE"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/test.mt"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/test.tag"
    - "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/test.hter"
  vocabularies:
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/vocab.en.json"
      max_n_words: -1
    - type: "word"
      dict_path: "/home/data_ti4_c/yanym/qe/data/wmt20_enzh/bpe_not_mine/vocab_big.zh.json"
      max_n_words: -1
  max_len:
    - -1
    - -1
  num_refs: 1
  eval_at_char_level: false

discriminator_configs:
  model: Discriminator
  n_layers: 6
  n_head: 8
  n_labels: 3
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 1024
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.0

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.0001
  weight_decay: 0
  grad_clip: 1.0
  optimizer_params: ~
  schedule_method: ~
  scheduler_configs:
    d_model: 512
    warmup_steps: 100

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: false
  use_bucket: false
  buffer_size: 1000
  batch_size: 1
  batching_key: "samples"
  update_cycle: 30
  valid_batch_size: 1
  disp_freq: 60
  save_freq: 1200
  num_kept_checkpoints: 1
  loss_valid_freq: 1200
  early_stop_patience: 10
